MadLearners/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # re_path(r'^$', views.index, name='index'),
    
    path('admin/', admin.site.urls),

    path('account/',include('accounts.urls')),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('videos/', include('video.urls')),
    path('api/', include('api.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path, re_path, include
from api import views


# /MadLearners/

urlpatterns = [
    # re_path(r'^$', views.index, name='MadLearners'),
    path('blogapi/',views.blogAPI),
    path('categoryapi/',views.categoryAPI),
    path('videoapi/',views.videoAPI),

    # path('login/', views.LoginView.as_view()),
    # path('logout/', views.LogoutView.as_view()),



    path('auth/',include('djoser.urls')),
    path('auth/',include('djoser.urls.authtoken')),
    # path('register/', views.registration_view, name="register"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import mark_safe

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    featured_image = models.ImageField(upload_to='blog/categories',default ='common/placeholder.png')
    description = models.TextField(blank=True)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

class Blog(models.Model):
    title = models.CharField(max_length=200, unique=False)
    author = models.CharField(max_length=30, unique=False)
    slug = models.SlugField(max_length=200, unique=True)
    featured_image = models.ImageField(upload_to='blog',default ='common/placeholder.png')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, unique=False)
    featured = models.BooleanField(default=False)
    content = models.TextField()
    date = models.DateField()
    is_approved = models.BooleanField(default=False)
    def __str__(self):
        return self.title

templates/main_app/contact.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block Title %}
Contact
{% endblock Title %}

{% block mformactive %}active{% endblock mformactive %}

{% block body_block %}

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">CONTACT</h1>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Contact</li>
        </ol>
      </nav>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col mb-3">
      <div class="card">
        <div class="card-header bg-primary text-white"><i class="fa fa-envelope"></i> Contact us
        </div>
        <div class="card-body">


          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="name">Name</label>
              <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" required>
            </div>
            <div class="form-group">
              <label for="email">Email address</label>
              <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="message">Message</label>
              <textarea class="form-control" id="message" name="message" rows="6" required></textarea>
            </div>
            <div class="mx-auto">
              <button type="submit" class="btn btn-primary text-right">Submit</button></div>
          </form>


        </div>
      </div>
    </div>
    <div class="col-12 col-lg-4">
      <div class="card bg-light mb-3">
        <div class="card-header bg-success text-white text-uppercase"><i class="fa fa-home"></i> Contact Information
        </div>
        <div class="card-body">
          <p>Email : info@madlearners.com</p>
          <p>Mod. +918865026263</p>

        </div>

      </div>
    </div>
  </div>
</div>

{% comment %} <div class="container  my-3">
  <h1 class="text-center">Contact</h1>

  <form method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
    </div>
    <div class="form-group">
      <label for="email">Email address</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
    </div>
    <div class="form-group">
      <label for="message">Message</label>
      <textarea class="form-control" id="message" name="message" placeholder="Enter Your Message Here" rows="3"
        required></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form> {% endcomment %}

  {% comment %} <form method="POST">
    {{ cform.as_p }}
    {% csrf_token %}
    <input type="submit" class='btn btn-primary' value="Submit">
  </form> {% endcomment %}
  {% comment %}
</div> {% endcomment %}
{% endblock body_block %}

templates/main_app/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block Title %}Home{% endblock Title %}
{% block homeactive %}active{% endblock homeactive %}

{% block body_block %}
<section class="jumbotron text-center">
    <div class="container">
        {% if user.i2s_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
        {% endif %}
        <img src="{% static 'images/logo.png' %}" alt="logo" width="120">

        <h1 class="jumbotron-heading">

            <span href="" class="typewrite" data-period="1000"
                data-type='[ "Crazy", "For", "Learning", "Something", "New" ]'>
                <span class="wrap"></span>
        </h1>
        {% comment %} {% lorem 1 p %} {% endcomment %}
        <p>
            <a href="{% url 'blog' %}" target="_blank" class="btn btn-danger my-2">Browse Blog</a>
            <a href="{% url 'videos' %}" target="_blank" class="btn btn-success my-2">Browse Recommended Videos</a>
            <a href="{% url 'contact' %}" target="_blank" class="btn btn-primary my-2">Contact Me</a>
        </p>

    </div>
</section>

<div class="container  my-3">
    <h1 class="page-header">
        Recent Blogs</h1>
    {% for post in allpost %}
    <hr>
    <h2><a href="blog/{{post.slug}}" class="text-dark">{{post.title}}</a></h2>
    <p>{{post.content|safe|truncatechars_html:200}}</p>
    <a class="btn btn-sm btn-outline-danger" href="blog/{{post.slug}}">Read More <span
            class="glyphicon glyphicon-chevron-right"></span></a>
    <hr>

    {% endfor %}
</div>
{% endblock body_block %}

templates/main_app/my_articles.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block Title %}My Articles{% endblock Title %}

{% block body_block %}
<div class="container  my-3">

    <div class="col-lg-12 my-2 mx-2">
        <h1>My Articles</h1>
        {% for post in allpost %}
        <hr>
        <h2><a href="blog/{{post.slug}}" class="text-dark">{{post.title}}</a></h2>
        <p>{{post.content|safe|truncatechars_html:200}}</p>
        <a class="btn btn-sm btn-outline-danger" href="blog/{{post.slug}}">Read More <span
                class="glyphicon glyphicon-chevron-right"></span></a>
        <hr>
    
        {% endfor %}
        
    </div>

</div>

{% endblock body_block %}

templates/main_app/privacy-policy.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block Title %}Privacy Policy{% endblock Title %}

{% block body_block %}
<div class="container my-5">
<h2>Privacy Policy</h2>
Mad Learners built this app as
a Free app. This SERVICE is provided by
Mad Learners at no cost and is intended for
use as is.
<br />

This page is used to inform visitors regarding
my policies with the collection, use, and
disclosure of Personal Information if anyone decided to use
my Service.
<br />

If you choose to use my Service, then you agree
to the collection and use of information in relation to this
policy. The Personal Information that I collect is
used for providing and improving the Service.
I will not use or share your
information with anyone except as described in this Privacy
Policy.
<br />

The terms used in this Privacy Policy have the same meanings
as in our Terms and Conditions, which is accessible at
this app unless otherwise defined in this Privacy
Policy.
<br />
<strong>Information Collection and Use</strong><br />

For a better experience, while using our Service,
I may require you to provide us with certain
personally identifiable information. The
information that I request will be
retained on your device and is not collected by me in any way.
<br />

The app does use third party services that may collect
information used to identify you.
<br />
<div>
  Link to privacy policy of third party service providers
  used by the app
  <br />
  <ul>
    <li><a href="https://www.google.com/policies/privacy/" target="_blank">Google Play Services</a></li>
    <li><a href="https://support.google.com/admob/answer/6128543?hl=en" target="_blank">AdMob</a></li>
    <li><a href="https://firebase.google.com/policies/analytics" target="_blank">Firebase Analytics</a></li>
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
    <!---->
  </ul>
</div>
<strong>Log Data</strong><br />

I want to inform you that whenever
you use my Service, in a case of an error in the
app I collect data and information (through third
party products) on your phone called Log Data. This Log Data
may include information such as your device Internet
Protocol (“IP”) address, device name, operating system
version, the configuration of the app when utilizing
my Service, the time and date of your use of the
Service, and other statistics.
<br />
<strong>Cookies</strong><br />

Cookies are files with a small amount of data that are
commonly used as anonymous unique identifiers. These are
sent to your browser from the websites that you visit and
are stored on your device's internal memory.
<br />

This Service does not use these “cookies” explicitly.
However, the app may use third party code and libraries that
use “cookies” to collect information and improve their
services. You have the option to either accept or refuse
these cookies and know when a cookie is being sent to your
device. If you choose to refuse our cookies, you may not be
able to use some portions of this Service.
<br />
<strong>Service Providers</strong><br />

I may employ third-party companies
and individuals due to the following reasons:
<br />
<ul>
  <li>To facilitate our Service;</li>
  <li>To provide the Service on our behalf;</li>
  <li>To perform Service-related services; or</li>
  <li>To assist us in analyzing how our Service is used.</li>
</ul>
I want to inform users of this
Service that these third parties have access to your
Personal Information. The reason is to perform the tasks
assigned to them on our behalf. However, they are obligated
not to disclose or use the information for any other
purpose.
<br />
<strong>Security</strong><br />

I value your trust in providing us
your Personal Information, thus we are striving to use
commercially acceptable means of protecting it. But remember
that no method of transmission over the internet, or method
of electronic storage is 100% secure and reliable, and
I cannot guarantee its absolute security.
<br />
<strong>Links to Other Sites</strong><br />

This Service may contain links to other sites. If you click
on a third-party link, you will be directed to that site.
Note that these external sites are not operated by
me. Therefore, I strongly advise you to
review the Privacy Policy of these websites.
I have no control over and assume no
responsibility for the content, privacy policies, or
practices of any third-party sites or services.
<br />

<strong>Changes to This Privacy Policy</strong><br />

I may update our Privacy Policy from
time to time. Thus, you are advised to review this page
periodically for any changes. I will
notify you of any changes by posting the new Privacy Policy
on this page. These changes are effective immediately after
they are posted on this page.
<br />
<strong>Contact Us</strong><br />

If you have any questions or suggestions about
my Privacy Policy, do not hesitate to contact
me at namanmalik2811@gmail.com.
<br />

</div>
{% endblock body_block %}

templates/main_app/profile.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block Title %}My Profile{% endblock Title %}

{% block body_block %}
<div class="container  my-3">

<div class="col-lg-12 my-2 mx-2">
        <h1>Update Profile</h1>
        <form method="post" action="">
        {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Name</label>
                    <input type="name" name="userName" value="" class="form-control" id="userName" placeholder="Your Name">
                </div>
                <div class="form-group col-md-6">
                    <label for="inputPassword4">Email</label>
                    <input type="email" name="userEmail" class="form-control" value="" id="userEmail" placeholder="Your Email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAddress">Your Phone</label>
                <input type="phone" name="userPhone" class="form-control" id="UserPhone" value="" placeholder="Your Phone">
            </div>
            
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>


    <div class="col-lg-12 my-2 mx-2">
        <h1>Change your password</h1>
        <form action="/profile/myaccount" method="post">
        {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-12">
                    <label for="pass">Your Password</label>
                    <input type="password" class="form-control" id="pass" name="pass" placeholder="Your Password">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="pass1">New Password</label>
                    <input type="password" class="form-control" id="pass1" name="pass1" placeholder="New Password">
                </div>
                <div class="form-group col-md-6">
                    <label for="pass2">Confirm New Password</label>
                    <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Confirm New Password">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>

</div>
{% endblock body_block %}

templates/main_app/submit_article.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block Title %}Submit An Article{% endblock Title %}

{% block body_block %}
<div class="container  my-3">

    <div class="col-lg-12 my-2 mx-2">
        <h1>Submit An Article</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title</label>
                <input type="title" name="title" class="form-control" id="title" placeholder="Title">
            </div>
            <div class="form-group">
                <label for="category">Category</label>
                <select name="category" class="form-control" id="category">
                    {% for cat in allcat %}
                    <option>{{cat.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label class="form-label" for="image">Featured Image</label>
                <input name="image" accept="image/*" type="file" class="form-control" id="image" />
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <input name="content" class="form-control" id="id_content">
            </div>

            <button type="submit" class="btn btn-primary">Submit for review</button>
        </form>
    </div>

</div>
<script type="text/javascript" src="{% static 'scripts/tinyinject.js' %}">
</script>

{% endblock body_block %}